-- Library Management System Project

-- Creating Branch Table

CREATE TABLE BRANCH (
	BRANCH_ID VARCHAR(10) PRIMARY KEY,
	MANAGER_ID VARCHAR(10) NOT NULL,
	BRANCH_ADDRESS VARCHAR(60),
	CONTACT_NO VARCHAR(15)
);

-- Creating Employee Table

CREATE TABLE EMPLOYEES (
	EMP_ID VARCHAR(10) PRIMARY KEY,
	EMP_NAME VARCHAR(30),
	POSITION VARCHAR(30),
	SALARY INT,
	BRANCH_ID VARCHAR(15)
);

-- Creating Books Table

CREATE TABLE BOOKS (
	ISBN VARCHAR(20) PRIMARY KEY,
	BOOK_TITLE VARCHAR(80),
	CATEGORY VARCHAR(25),
	RENTAL_PRICE FLOAT,
	STATUS VARCHAR(15),
	AUTHOR VARCHAR(35),
	PUBLISHER VARCHAR(50)
);

-- Creating Members Table

CREATE TABLE MEMBERS (
	MEMBER_ID VARCHAR(10) PRIMARY KEY,
	MEMBER_NAME VARCHAR(30),
	MEMBER_ADDRESS VARCHAR(80),
	REG_DATE DATE
);

-- Creating Issued_Status Table

CREATE TABLE ISSUED_STATUS (
	ISSUED_ID VARCHAR(10) PRIMARY KEY,
	ISSUED_MEMBER_ID VARCHAR(10),
	ISSUED_BOOK_NAME VARCHAR(75),
	ISSUED_DATE DATE,
	ISSUED_BOOK_ISBN VARCHAR(25),
	ISSUED_EMP_ID VARCHAR(10)
);

-- Creating Return_status Table

CREATE TABLE RETURN_STATUS (
	RETURN_ID VARCHAR(10) PRIMARY KEY,
	ISSUED_ID VARCHAR(10),
	RETURN_BOOK_NAME VARCHAR(75),
	RETURN_DATE DATE,
	RETURN_BOOK_ISBN VARCHAR(20)
);


-- Adding Foreign Key Constraints

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT FK_MEMBERS 
FOREIGN KEY (ISSUED_MEMBER_ID) 
REFERENCES MEMBERS (MEMBER_ID);

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT FK_BOOKS 
FOREIGN KEY (ISSUED_BOOK_ISBN) 
REFERENCES BOOKS (ISBN);

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT FK_EMPLOYEES 
FOREIGN KEY (ISSUED_BOOK_ISBN) 
REFERENCES EMPLOYEES (EMP_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_BRANCH 
FOREIGN KEY (BRANCH_ID) 
REFERENCES BRANCH (BRANCH_ID);

ALTER TABLE RETURN_STATUS
ADD CONSTRAINT FK_RETURN 
FOREIGN KEY (ISSUED_ID) 
REFERENCES ISSUED_STATUS (ISSUED_ID);






